baseURL = "https://ie.helpso.me/"
languageCode = "en-us"
title = "FAQ"
theme = "kraiklyn"
pluralizelisttitles = "false"

copyright = "CC BY-SA"
metaDataFormat = "yaml"
enableRobotsTXT = "true"

[params]
externalTitle = ""
sidebarColor = "default"
customCss = []
